ARG NODE_IMAGE
ARG CADDY_IMAGE
FROM ${NODE_IMAGE} AS studio
WORKDIR /app
COPY package.json package-lock.json ./
COPY web/package.json web/package.json
RUN npm ci
COPY web ./web
RUN npm run build

FROM ${CADDY_IMAGE}
# High internal ports allow dropping all capabilities; remove upstream file capability.
RUN setcap -r /usr/bin/caddy
COPY --from=studio /app/web/dist /srv/studio
COPY deploy/reverse-proxy/Caddyfile /etc/caddy/Caddyfile
USER 1000:1000
