// Explicit icon registry to avoid computed namespace access on the
// `lucide-react` namespace (which eslint-plugin-import flags and which
// pulls in the entire icon set). Add new icons here as needed.
import {
  Home,
  Compass,
  LibraryBig,
  Heart,
  ListMusic,
  Clock,
  Bell,
  User,
  Settings,
  LayoutGrid,
  Mic,
  Radio,
  BarChart3,
  Share2,
  Users,
  DollarSign,
  UserPlus,
  FolderOpen,
  CreditCard,
  Tags,
  ShieldAlert,
  Flag,
  LifeBuoy,
  Briefcase,
  Rocket,
  GraduationCap,
  Cpu,
  Sparkles,
  LineChart,
  Building2,
  TrendingUp,
  Hash,
  Circle,
} from 'lucide-react';

export const iconMap = {
  Home,
  Compass,
  LibraryBig,
  Heart,
  ListMusic,
  Clock,
  Bell,
  User,
  Settings,
  LayoutGrid,
  Mic,
  Radio,
  BarChart3,
  Share2,
  Users,
  DollarSign,
  UserPlus,
  FolderOpen,
  CreditCard,
  Tags,
  ShieldAlert,
  Flag,
  LifeBuoy,
  Briefcase,
  Rocket,
  GraduationCap,
  Cpu,
  Sparkles,
  LineChart,
  Building2,
  TrendingUp,
  Hash,
  Circle,
};

export function getIcon(name, fallback = 'Circle') {
  return iconMap[name] || iconMap[fallback] || Circle;
}
